name: fit-friends
services:
  mongo:
    image: mongo:4.4
    restart: always
    container_name: mongo

    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: test

    ports:
      - 27018:27017

    volumes:
      - mongo:/data/db

    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/admin --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  mongo.ui:
    image: mongo-express:1.0-20
    restart: always
    container_name: mongo.ui

    ports:
      - 8082:8081

    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: test
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: test
      ME_CONFIG_MONGODB_URL: mongodb://admin:test@mongo:27017/

  fakesmtp:
    image: gessnerfl/fake-smtp-server:2.2.0
    container_name: fakesmtp

    ports:
      - 8025:8025
      - 1085:8080

  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbitmq

    ports:
      - 1088:15672
      - 5672:5672

    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: test

    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo:
