# //! разбить на отдельные в сервисах, задействовать env
name: fit-friends
services:
  mongo:
    image: mongo:4.4
    restart: always
    container_name: mongo

    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: test

    ports:
      - 27018:27017

    volumes:
      - mongo:/data/db

    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/admin --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  mongo.ui:
    image: mongo-express:1.0-20
    restart: always
    container_name: mongo.ui

    ports:
      - 8082:8081

    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: test
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: test
      ME_CONFIG_MONGODB_URL: mongodb://admin:test@mongo:27017/

    depends_on:
      - mongo

  postgres:
    image: postgres:14-alpine
    container_name: postgres

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: test

    ports:
      -  5433:5432

    volumes:
      - postgres:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin

    environment:
      PGADMIN_DEFAULT_EMAIL: =admin@test.ru
      PGADMIN_DEFAULT_PASSWORD: test
      PGADMIN_CONFIG_SERVER_MODE: "False"

    ports:
      - 8084:80

    depends_on:
      - postgres

  fakesmtp:
    image: gessnerfl/fake-smtp-server:2.2.0
    container_name: fakesmtp

    ports:
      - 8025:8025
      - 1085:8080

  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbitmq

    ports:
      - 1088:15672
      - 5672:5672

    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: test

    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo:
  postgres:
