@baseUrl = http://localhost:3000/api
@baseUrlAuth = {{baseUrl}}/users

# Create a new user - Content-Type: application/json
POST {{baseUrlAuth}}/register HTTP/1.1
Content-Type: application/json

{
  "name": "Name",
  "email": "user@local.local",
  "password": "password",
  "birthday": "2005-01-20",
  "metroStationName": "pionerskaya",
  "backgroundPath": "/some/path/img.jpg",
  "gender": "male",
  "role": "sportsman"
}

###

# Create a new user with avatarFile - Content-Type: multipart/form-data
POST {{baseUrlAuth}}/register HTTP/1.1
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="email"

user1@local.local
--boundary
Content-Disposition: form-data; name="name"

Keks
--boundary
Content-Disposition: form-data; name="name1111"

Keks1111
--boundary
Content-Disposition: form-data; name="password"

123456
--boundary
Content-Disposition: form-data; name="metroStationName"

pionerskaya
--boundary
Content-Disposition: form-data; name="backgroundPath"

/some/path/img.jpg
--boundary
Content-Disposition: form-data; name="gender"

male
--boundary
Content-Disposition: form-data; name="role"

sportsman
--boundary
Content-Disposition: form-data; name="avatarFile"; filename="cat.jpg"
Content-Type: image/png

< ../../../../../markup/img/content/avatars/users/photo-1.png
--boundary--

###

# Login user by email and password
POST {{baseUrlAuth}}/login HTTP/1.1
Content-Type: application/json

{
  "email": "user@local.local",
  "password": "123456"
}

###

# Get new JWT pair
POST {{baseUrlAuth}}/refresh HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NzdlNWYzMTVjODE2NmIyZWE3ZjcwMTUiLCJlbWFpbCI6InVzZXJAbG9jYWwubG9jYWwiLCJuYW1lIjoiS2VrcyIsInRva2VuSWQiOiIxYmI3OWVkZi05MmQ5LTQwNjUtYTlhNS1mZjRkMjFkYTQ3YTAiLCJpYXQiOjE3MzY3NDc4NjYsImV4cCI6MTczOTMzOTg2Nn0.p_3sMwRZ-5bhCp9wNQabL1phSdVo0o5x0iDDjasFpD8

###

# Check user token
POST {{baseUrlAuth}}/check HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NzdlNWYzMTVjODE2NmIyZWE3ZjcwMTUiLCJlbWFpbCI6InVzZXJAbG9jYWwubG9jYWwiLCJuYW1lIjoiS2VrcyIsImlhdCI6MTczNjc0Nzg2NiwiZXhwIjoxNzM2NzQ4MTY2fQ.1BHbfTjaWESWSoNauE-R79JgsBT9WesglhwN3LHtZtw

###

# Get user by ID
GET {{baseUrlAuth}}/677e5f315c8166b2ea7f7015 HTTP/1.1

###
